version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies", "wdem"]
    commit-message:
      prefix: "deps(wdem)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies", "wdem"]
    commit-message:
      prefix: "deps(wdem)"
