<Project>
  <PropertyGroup>
    <Product>Windows Developer Environment Manager</Product>
    <Authors>Jason Li</Authors>
    <Copyright>Copyright © 2026 Jason Li</Copyright>
    <VersionPrefix>0.1.1</VersionPrefix>
    <RepositoryUrl>https://github.com/JasonLiCSHI/WDEM</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
