blank_issues_enabled: false
contact_links:
  - name: WDEM GitHub Discussions
    url: https://github.com/JasonLiCSHI/WDEM/discussions
    about: Please use discussions for questions or support.
  - name: WDEM contribution guidelines
    url: https://github.com/JasonLiCSHI/WDEM/blob/main/CONTRIBUTING.md
    about: Read our contribution guide before opening an issue.
